#!/usr/bin/python3
"""Defines an island perimeter measuring function."""


def island_perimeter(grid):
    """Return the param of an island.

    The grid use water by 0 and land by 1.

    Args:
        grid (list): A list of list of int representing an island.

    Returns:
        The param of the island defined in grid.
    """
    height = len(grid)
    width = len(grid[0])
    edges = 0
    size = 0

    for i in range(height):
        for j in range(width):
            if grid[i][j] == 1:
                # Count the number of edges around the land
                if i > 0 and grid[i - 1][j] == 1:
                    edges += 1
                if j > 0 and grid[i][j - 1] == 1:
                    edges += 1
                # Count the number of cells in the island
                size += 1

    return size * 4 - edges * 2

